# Movies Domain Configuration
# For processing feature films, trailers, and cinematic content
# Supports multilingual audio with optional automatic language detection

domain:
  name: "movies"
  description: "Processing feature films, trailers, and cinematic content with multilingual support"

models:
  age_gender: "audeering/wav2vec2-large-robust-6-ft-age-gender"
  whisper: "openai/whisper-large-v3"  # Multilingual transcription
  gemini: "gemini-2.0-flash"
  deepgram: "nova-2-general"

features:
  diarization: true
  entity_intent_extraction: true
  structured_summary: true
  gemini_transcription: true  # Use Whisper as primary
  deepgram_transcription: true

processing:
  chunk_duration: 30.0  # seconds
  overlap_duration: 10.0  # seconds
  min_speakers: 1
  max_speakers: 20  # Ensemble casts and crowd scenes

# NOTE: Set to "english" for English-only, or set to null for Whisper auto language detection
language: "english"

input:
  # IMPORTANT: Update this path to your movie audio/video files
  directory: "/external4/datasets/strem2action-audio/movies_data"
  extensions: [".wav", ".mp3", ".mp4", ".mkv", ".webm", ".m4a"]

output:
  # IMPORTANT: Update this path for the processed output
  directory: "/external4/datasets/strem2action-audio/movies_data"
  per_file_subdirs: true  # Keep outputs alongside each movie/scene

prompts:
  gemini_transcription: |
    Transcribe this movie audio accurately, preserving natural dialogue and pacing.
    Pay attention to character names, proper nouns, cultural references, locations,
    and multilingual content or code-switching. Maintain speaker distinctions and tone.
    Output only the transcript without any extra formatting.

  gemini_entities_intents: |
    Extract film-related entities and intents from the following text.

    Entities to extract (with type labels):
    - MOVIE_TITLE: Title of the film (or referenced films).
    - CHARACTER_NAME: Names of characters appearing in the scene.
    - ACTOR_NAME: Real names of actors (for interviews/BTS dialogue).
    - DIRECTOR: The film's director if mentioned.
    - WRITER: Screenwriter names if mentioned.
    - PRODUCER: Producer names or production companies.
    - STUDIO: Name of the studio or distributor.
    - LOCATION: Cities, countries, fictional places, or sets.
    - SCENE: Named scene or sequence identifiers (e.g., "bank heist scene").
    - OBJECT: Important props or items (e.g., "briefcase", "ring").
    - VEHICLE: Vehicles referenced (e.g., "Mustang", "spaceship").
    - WEAPON: Weapons referenced (e.g., "sword", "pistol").
    - SOUNDTRACK_SONG: Songs or musical pieces mentioned.
    - ORGANIZATION: Groups, gangs, agencies, institutions.
    - EMOTIONAL_STATE: Emotion expressed (joy, grief, anger, fear, etc.).
    - RELATIONSHIP: Familial or social relationships between characters.
    - TIME_REFERENCE: Dates, times, historical periods, temporal markers.
    - CULTURAL_REFERENCE: Pop-culture or cultural-specific references.
    - GENRE_ELEMENT: Tropes like chase, heist, duel, montage, plot twist.
    - LANGUAGE: Language being spoken when relevant.

    Intents to identify:
    - DIALOGUE: Characters conversing.
    - NARRATION: Voice-over narration.
    - EXPOSITION: Background or world-building information.
    - CONFLICT: Arguments or confrontations.
    - HUMOR: Jokes and comedic beats.
    - EMOTION_EXPRESSION: Explicit feelings or inner states.
    - ACTION_DESCRIPTION: Description of action or set pieces.
    - PLOT_DEVELOPMENT: Moves the story forward.
    - CHARACTER_DEVELOPMENT: Reveals character traits or growth.
    - FORESHADOWING: Hints at future events.
    - FLASHBACK: References to past events.
    - MONTAGE: Condensed sequence of events.
    - MUSICAL_PERFORMANCE: Songs or diegetic performances.

    Return JSON format:
    {
      "entities": [
        {"text": "entity text", "type": "ENTITY_TYPE", "language": "detected_language"},
        ...
      ],
      "intents": ["INTENT_1", "INTENT_2", ...],
      "languages_detected": ["language1", "language2", ...]
    }

    Text to analyze:

  gemini_structured: |
    Extract a structured summary of this movie scene or segment.

    Return JSON with these fields (include only if present):
    {
      "movie_title": "Name of the film (if identifiable)",
      "scene_summary": "Brief summary of the scene or segment",
      "main_characters": ["primary characters in this segment"],
      "supporting_characters": ["secondary characters"],
      "setting": "Primary location(s) or setting",
      "plot_points": ["key story developments in order"],
      "emotional_arc": "Emotional journey across the scene",
      "comedic_moments": ["notable jokes or humor"],
      "dramatic_moments": ["serious or tense moments"],
      "relationships_explored": ["character relationships featured"],
      "themes": ["underlying themes or messages"],
      "soundtrack_songs": ["songs or musical cues mentioned"],
      "languages_present": ["languages spoken in this content"],
      "code_switching_instances": ["moments where language switches occur"],
      "climax_or_resolution": "How the segment resolves (if applicable)",
      "genre": "action|drama|thriller|comedy|romance|sci-fi|fantasy|horror|documentary|animation|mixed",
      "tone": "lighthearted|serious|suspenseful|satirical|emotional|dark|mixed",
      "audience_engagement_markers": ["beats designed to engage viewers"]
    }

    Movie content:

# Multilingual processing settings
multilingual:
  enabled: true
  primary_languages: ["english", "hindi", "spanish", "french", "german", "japanese", "korean", "chinese"]
  handle_code_switching: true
  translate_to_english: false  # Set true to include translations

entity_types:
  - "MOVIE_TITLE"
  - "CHARACTER_NAME"
  - "ACTOR_NAME"
  - "DIRECTOR"
  - "WRITER"
  - "PRODUCER"
  - "STUDIO"
  - "LOCATION"
  - "SCENE"
  - "OBJECT"
  - "VEHICLE"
  - "WEAPON"
  - "SOUNDTRACK_SONG"
  - "ORGANIZATION"
  - "EMOTIONAL_STATE"
  - "RELATIONSHIP"
  - "TIME_REFERENCE"
  - "CULTURAL_REFERENCE"
  - "GENRE_ELEMENT"
  - "LANGUAGE"

intent_categories:
  - "DIALOGUE"
  - "NARRATION"
  - "EXPOSITION"
  - "CONFLICT"
  - "HUMOR"
  - "EMOTION_EXPRESSION"
  - "ACTION_DESCRIPTION"
  - "PLOT_DEVELOPMENT"
  - "CHARACTER_DEVELOPMENT"
  - "FORESHADOWING"
  - "FLASHBACK"
  - "MONTAGE"
  - "MUSICAL_PERFORMANCE"
