# TV Show Domain Configuration
# For processing television show episodes, series, and entertainment content
# Supports multilingual audio with automatic language detection

domain:
  name: "tv_show"
  description: "Processing TV show episodes, series, and entertainment content with multilingual support"

models:
  age_gender: "audeering/wav2vec2-large-robust-6-ft-age-gender"
  whisper: "openai/whisper-large-v3"  # Supports multilingual transcription
  gemini: "gemini-2.0-flash"
  deepgram: "nova-2-general"

features:
  diarization: true
  entity_intent_extraction: true
  structured_summary: true
  gemini_transcription: false  # Use Whisper as primary for multilingual support
  deepgram_transcription: false

processing:
  chunk_duration: 30.0  # seconds
  overlap_duration: 10.0  # seconds
  min_speakers: 1  # For single-person shows or narration
  max_speakers: 10  # For ensemble casts or panel shows

language: "english"  # Automatic language detection for multilingual content

input:
  # IMPORTANT: Update this path to your TV show audio files
  directory: "/external4/datasets/strem2action-audio/tvshow_data"
  extensions: [".wav", ".mp3", ".mp4", ".mkv", ".webm", ".m4a"]

output:
  # IMPORTANT: Update this path for the processed output
  directory: "/external4/datasets/strem2action-audio/tvshow_data"
  per_file_subdirs: true  # Separate output per episode/file

prompts:
  gemini_transcription: |
    Transcribe this TV show audio accurately, preserving the natural dialogue flow.
    Pay attention to character names, show-specific terminology, cultural references, 
    location names, and any multilingual content.
    Maintain speaker distinctions and emotional tone where evident.
    Output only the transcript without any formatting or extra text.

  gemini_entities_intents: |
    Extract TV show and entertainment-related entities and intents from the following text.
    
    Entities to extract (with type labels):
    - CHARACTER_NAME: Names of characters appearing in the show.
    - ACTOR_NAME: Real names of actors (if mentioned in behind-the-scenes or interviews).
    - LOCATION: Places, cities, fictional worlds, or settings mentioned.
    - SHOW_TITLE: Name of the show or related series/episodes.
    - EVENT: Significant plot events, ceremonies, or happenings.
    - OBJECT: Important props, items, or artifacts in the story.
    - ORGANIZATION: Companies, groups, factions, or institutions.
    - EMOTIONAL_STATE: Expressions of emotion (joy, anger, fear, surprise, etc.).
    - RELATIONSHIP: References to relationships between characters (friend, enemy, family, etc.).
    - TIME_REFERENCE: Temporal markers (past, present, future, specific dates/times).
    - CULTURAL_REFERENCE: Pop culture references, idioms, or cultural-specific phrases.
    - GENRE_ELEMENT: Comedy beats, dramatic moments, action sequences, musical numbers.
    - LANGUAGE: Language being spoken (for code-switching or multilingual content).
    
    Intents to identify:
    - DIALOGUE: Characters having a conversation.
    - NARRATION: Voice-over or narrator speaking.
    - EXPOSITION: Providing background information or context.
    - CONFLICT: Characters in disagreement or confrontation.
    - HUMOR: Jokes, comedic timing, or funny moments.
    - EMOTION_EXPRESSION: Character expressing feelings.
    - ACTION_DESCRIPTION: Describing or discussing action sequences.
    - PLOT_DEVELOPMENT: Moving the story forward.
    - CHARACTER_DEVELOPMENT: Revealing character traits or growth.
    - FORESHADOWING: Hinting at future events.
    - FLASHBACK: Referencing past events.
    - BREAKING_FOURTH_WALL: Direct address to the audience.
    - MUSICAL_PERFORMANCE: Singing or musical content.
    - COMMERCIAL_BREAK: Transition points or teases.
    
    Return JSON format:
    {
      "entities": [
        {"text": "entity text", "type": "ENTITY_TYPE", "language": "detected_language"},
        ...
      ],
      "intents": ["INTENT_1", "INTENT_2", ...],
      "languages_detected": ["language1", "language2", ...]
    }
    
    Text to analyze:

  gemini_structured: |
    Extract a structured summary of this TV show content.
    
    Return JSON with these fields (include only if present):
    {
      "show_title": "Name of the show (if identifiable)",
      "episode_summary": "Brief summary of the episode or scene",
      "main_characters": ["list of primary characters appearing"],
      "supporting_characters": ["list of secondary characters"],
      "setting": "Primary location(s) or setting",
      "plot_points": ["key story developments in order"],
      "emotional_arc": "Description of the emotional journey",
      "comedy_elements": ["list of comedic moments or jokes"],
      "dramatic_moments": ["list of serious or dramatic scenes"],
      "relationships_explored": ["character relationships featured"],
      "themes": ["underlying themes or messages"],
      "cultural_elements": ["cultural references, idioms, or context-specific content"],
      "languages_present": ["languages spoken in this content"],
      "code_switching_instances": ["moments where language switches occur"],
      "cliffhanger_or_resolution": "How the segment ends",
      "genre": "comedy|drama|thriller|action|romance|sci-fi|fantasy|documentary|reality|mixed",
      "tone": "lighthearted|serious|suspenseful|satirical|emotional|mixed",
      "audience_engagement_markers": ["moments designed to engage viewers"]
    }
    
    TV show content:

# Multilingual processing settings
multilingual:
  enabled: true
  primary_languages: ["english", "hindi", "spanish", "french", "german", "japanese", "korean", "chinese"]
  handle_code_switching: true  # Detect when speakers switch languages mid-conversation
  translate_to_english: false  # Set to true if you want translations alongside original

entity_types:
  - "CHARACTER_NAME"
  - "ACTOR_NAME"
  - "LOCATION"
  - "SHOW_TITLE"
  - "EVENT"
  - "OBJECT"
  - "ORGANIZATION"
  - "EMOTIONAL_STATE"
  - "RELATIONSHIP"
  - "TIME_REFERENCE"
  - "CULTURAL_REFERENCE"
  - "GENRE_ELEMENT"
  - "LANGUAGE"

intent_categories:
  - "DIALOGUE"
  - "NARRATION"
  - "EXPOSITION"
  - "CONFLICT"
  - "HUMOR"
  - "EMOTION_EXPRESSION"
  - "ACTION_DESCRIPTION"
  - "PLOT_DEVELOPMENT"
  - "CHARACTER_DEVELOPMENT"
  - "FORESHADOWING"
  - "FLASHBACK"
  - "BREAKING_FOURTH_WALL"
  - "MUSICAL_PERFORMANCE"
  - "COMMERCIAL_BREAK"
